server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
#    inetutils:
#      preferred-networks: 10.6.135
management:
  endpoints:
    web:
      exposure:
        include: '*'