server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 10.6.135.6:8080 #配置Nacos地址


management:
  endpoints:
    web:
      exposure:
        include: '*'
#logging:
#  file:
#    path: /app/log/
#    name: payment9001.log
